### ISSUE TITLE
Expose Scheduler Option

### ISSUE THREAD

**Issue by lockhartja** [sksamuel/aedile#14]
@sksamuel first awesome library -- thanks for the effort it took to make this available to the community. I was wondering if there currently exist a way to expose the scheduler option the [original library has documented?](https://github.com/ben-manes/caffeine/wiki/Cleanup)

**Comment by sksamuel** [comment]
@lockhartja What do you think to this PR. https://github.com/sksamuel/aedile/pull/15
Adding a scheduler option, where you pass in a function which returns a Deferred.
