### ISSUE TITLE
`get` method is typed as non-null but if the load function fails it will return null

### ISSUE THREAD

**Issue by jebbench** [sksamuel/aedile#18]
I have a `LoadingCache` where it's possible for the load function to throw, this causes the get call to return null.

In my scenario I'm caching files so I call get("http://my-url") which may result in a error (e.g. 404).

```
private val cache = caffeineBuilder<String, ByteArray>()
            .buildAll { urls ->
                // Download the URLs, may throw an exception or could swallow the exception and leave the result our of the returned map
            }
```

Preload the URLs
```
cache.getAll(urls)
```

Use the URLs
```
val r = cache.get(url)
if(r == null){ // The IDE complains "Condition 'r == null' is always 'false'" but this isn't true
    error("Null bytes for URL ${url}.")
}
```

**Comment by sksamuel** [comment]
Do you think its better if the call itself propagates the exception? That would seem to be the most intuitive to me.

**Comment by sksamuel** [comment]
There is a getOrNull method in 1.3.0 that will allow the call to return nulls.
