### ISSUE TITLE
Could you compile the jar using Java 8?

### ISSUE THREAD

**Issue by pengkui** [sksamuel/aedile#3]
It seems `aedile-core-1.1.2.jar` is compiled by Java 11 (version 55). 
https://s01.oss.sonatype.org/#nexus-search;quick~aedile

Ref: "java.lang.UnsupportedClassVersionError: com/sksamuel/aedile/core/Cache has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

Could you compile it using Java 8 (version 52) for the sake of compatibility?

Reasons we cannot use Java version higher than 8 include: (1) the kotlin-maven-plugin 1.6.x we use targets java 8, (2) we use maven-jar-plugin to build java 8 jars for other legacy systems to use, and (3) other practical reasons...

**Comment by sksamuel** [comment]
Caffeine itself is Java11 from 3.x so we can't release a 8 version of it.

**Comment by pengkui** [comment]
How about compiling `aedile-core-jdk8` for caffeine-2.9.x ...

**Comment by sksamuel** [comment]
This library is aimed at caffeine 3.0+
