### ISSUE TITLE
Cache.get() cancels coroutine when exception thrown

### ISSUE THREAD

**Issue by cloudshiftchris** [sksamuel/aedile#30]
Expecting `cache.get(key) { ... load value here ... }` to propagate exceptions to the caller, as documented:

> If the suspendable computation throws, the exception will be propagated to the caller.

What happens instead is the coroutine is cancelled and a JobCancellationException is thrown.

```
try {
    val cache = cacheBuilder<String, String>().build()

    cache.get("key") { throw IllegalArgumentException("Whoops") }
} catch (t: Throwable) {
    // this is a JobCancellationException; expected to be the thrown IllegalArgumentException
    println(t)
}
```

`Exception: kotlinx.coroutines.JobCancellationException: TimeoutCoroutine is cancelling; job=TimeoutCoroutine(timeMillis=45000){Cancelling}@609ac453` (this is inside a kotest test)

**Comment by cloudshiftchris** [comment]
Looking through the tests - they aren't up-to-date wrt `cacheBuilder` (most use `caffeineBuilder`) - the test for exception propagation works for `caffeineBuilder` but fails when changed to `cacheBuilder`

```
                // from unit test: https://github.com/sksamuel/aedile/blob/8d3ea128b474062dae9ad6b925f3f0c5d748a75d/aedile-core/src/test/kotlin/com/sksamuel/aedile/core/CacheTest.kt#L42
                // exception propagation works
                val cache = caffeineBuilder<String, String>().build()
                shouldThrow<IllegalStateException> {
                    cache.get("foo") {
                        error("kapow")
                    }
                }

                // using cacheBuilder instead
                // exception propagation fails - coroutine is cancelled
                val cache2 = cacheBuilder<String, String>().build()
                shouldThrow<IllegalStateException> {
                    cache2.get("foo") {
                        error("kapow")
                    }
                }
```

**Comment by jebbench** [comment]
Setting `useCallingContext` to false in the configuration block will cause the correct exception to be thrown - this is fine for our usecase but may not be useful in others.

```kotlin
private val urlCache = cacheBuilder<CacheKey, URL> {
    useCallingContext = false
    dispatcher = Dispatchers.Default
}.build()
```

**Comment by sksamuel** [comment]
Can you try the latest snapshot from https://s01.oss.sonatype.org/content/repositories/snapshots/com/sksamuel/aedile/aedile-core/
And update to use Caffeine.newBuilder directly, add in your config, then call .asCache or .asLoadingCache.
No other changes needed.
If you're happy with that, I will release 2.0.0. final.

**Comment by sksamuel** [comment]
Actually I threw out at 2.0.0.RC1 stable release to make it easier to test with.
