### ISSUE TITLE
Ideas for trivial convenience features that go beyond strict wrapping

### ISSUE THREAD

**Issue by sschuberth** [sksamuel/aedile#4]
I'm wondering whether it would be in scope of this project to maybe do a little bit more than strict wrapping, and add some (opinionated) convenience functions here and there. Specifically, I'm thinking about [persisting the cache between application runs](https://github.com/ben-manes/caffeine/discussions/828), which Caffeine is prepared for, but does not implement directly because "Java serialization is pretty bad" and "The intent is to [...] not [to] dictate how it should be done".

With Kotlin and [kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization), serialization is in good shape IMO, and using [Protobuf](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#ProtoBuf) could be a good candidate to save / restore the in-memory cache.

What do you think @sksamuel, would that be a reasonable functionality to add?

**Comment by sksamuel** [comment]
Hi @sschuberth 
In general, adding convenience functions == yes.
But for persisting a cache, that seems very specific functionality to me ?

**Comment by sschuberth** [comment]
> But for persisting a cache, that seems very specific functionality to me ?

Really? That's the first thing I was missing. But given that I'm not even using Caffeine / Aedile yet, I'm trusting on your guys here. Maybe I'm simply trying to use the wrong library for my purpose. So let me close this.
