### ISSUE TITLE
Support bulk mapping functions

### ISSUE THREAD

**Issue by jhuntbach-bc** [sksamuel/aedile#5]
With caffeine we can implement a `loadAll` [method](https://github.com/ben-manes/caffeine/discussions/588#discussioncomment-1278065) which allows us to bulk load the values for multiple keys in a single method call. The aedile Builder `build` method only allows us to implement single item loading.
```
fun build(compute: suspend (K) -> V): LoadingCache<K, V>
```

**Comment by sksamuel** [comment]
@jhuntbach-bc does this do what you want? 
https://github.com/sksamuel/aedile/pull/6
